### ISSUE TITLE
Add GPG sigs for rekor releases

### ISSUE THREAD

**Issue by udf2457** [sigstore/rekor#1399]
At the moment, your releases present a bit of a "chicken or egg" scenario.

You only provide rekor/cosign compatible signatures, which can only be verified with ... yes, that's right `cosign` and/or `rekor`.

So I would suggest there really there needs to be an out-of-band mechanism to enable people to verify `rekor` binaries when they don't have a pre-existing installation.

**Comment by asraa** [comment]
Hey! Thanks for the feedback.

We'd generally like to avoid GPG signatures. While it's true that we sign releases with keyless, we ALSO sign with ECDSA.

If you check the release [artifacts](https://github.com/sigstore/rekor/releases/tag/v1.0.1), you'll find `-keyless.sig` and a `.sig`. The `.sig` are signed with ECDSA and can be verified with openssl.

For example:

```
$ base64 -d rekor-cli-darwin-amd64.sig  > rekor-cli-darwin-amd64.sig.decoded
$ openssl dgst -sha256 -verify artifact.pub -signature rekor-cli-darwin-amd64.sig.decoded rekor-cli-darwin-amd64
```

You may be wondering where the public key `artifact.pub` can be found. This is distributed via our TUF repository hosted at https://github.com/sigstore/root-signing. You can find it in the latest repository [here](https://github.com/sigstore/root-signing/blob/main/repository/repository/targets/59ebf97a9850aecec4bc39c1f5c1dc46e6490a6b5fd2a6cacdcac0c3a6fc4cbf.artifact.pub)

[TUF](https://theupdateframework.io/) is a compromise-resilient software update system that allows us to distribute our public key material with secure updates. We [livestreamed](https://github.com/sigstore/root-signing#initial-root-signing-ceremony) the first root creation to bootstrap initial trust. You can verify and fetch the latest signing key with a TUF client, like python-tuf, go-tuf, or tuftool. 

We have some instructions on the Fulcio repository for how to use a TUF client. https://github.com/sigstore/fulcio#public-instance
You can follow these instructions, but get the `artifact.pub` instead, which is our release signing key.

Hope that helps!

**Comment by udf2457** [comment]
Interesting, thanks @asraa , although I seem to be falling at the first hurdle:

```
tuf-client init https://sigstore-tuf-root.storage.googleapis.com sigstore-root.json
ERROR: tuf: error unmarshalling key: invalid PEM value
```

**Comment by asraa** [comment]
Nice, that's expected now.

The `tuf-client` had a backwards incompatible change because it used to not be specification compliant (and so out original root.json was not spec compliant).

Pull the `5.root.json` in your line instead of `sigstore-root.json` where we became specification compliant.
```
curl -o sigstore-root.json https://raw.githubusercontent.com/sigstore/root-signing/main/ceremony/2022-10-18/repository/5.root.json
```

If you'd like to test from the original root and verify root version 1 to root version 5, you need to add the deprecated PEM key formats. You can see this in this workflow here, and use the binary there if you want to compile it with the deprecated fields. https://github.com/sigstore/root-signing/blob/f9b2714260d9d7fcc4747e1b740ed316f6ce28f9/.github/workflows/tuf_client_tests.yml#L53

All TUF clients will understand version 5 onwards.

The Fulcio docs need updating... @haydentherapper

**Comment by Hayden-IO** [comment]
https://github.com/sigstore/fulcio/pull/1079 (will move the release verifying documentation to docs.sigstore.dev)

**Comment by Hayden-IO** [comment]
Marking this issue as completed
