### ISSUE TITLE
New Project Name

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#155]
Signlog
Signsafe
Arbiter
Keysign
Hashsign
Treesign
Software transparency (like  certificate transparency)
Lets sign
Agano (translation of ‘testament’)
Teist (translation of ‘testament’)
Nema (translation of ‘testament’)
Zavet (translation of ‘testament’)
Teken (afrikaans for ‘sign’) 
Dentro (greek translation for 'tree')
Trie (a digital tree) https://en.wikipedia.org/wiki/Trie
Arianna, Ariane or Ariadne
Theseus
Lavra
Deadelus
Knossos
Hansel
Gretel
Hansel-Gretel

Please make a comment and I will add to the list.

**Comment by axelsimon** [comment]
Here are a few ideas i've had.
I've tried to follow a few themes.
First, the idea of Rekor as a thread, that you can follow to safety, out of a labyrinth but also to follow the provenance and all that.
- Arianna, Ariane or Ariadne
- Theseus

Labyrinth seems a bit obvious, but it's likely origin:
- Lavra

is quite cool  (it means small street or alley in a city in ancient Greek, Wikipedia tells me)

- Deadelus
- Knossos (the city where Daedelus's labyrinth would have been possibly built)

The other theme is bread crumbs, the bread crumb trail etc.
So possibly:
- Hansel or 
- Gretel

I don't like this as much.

I like the idea of using the leaf and tree nature of the Merkle tree, so that could be a nice theme too. I'll try and see if anything comes out of that on my end.

Recap:
- Arianna, Ariane or Ariadne
- Theseus
- Lavra
- Deadelus
- Knossos
- Hansel
- Gretel
- Hansel-Gretel

**Comment by lukehinds** [comment]
All done, we had to move quickly so we are now SigStore.
