### ISSUE TITLE
How important is it to start the rekor ledger in a projects lifecycle?

### ISSUE THREAD

**Issue by d3287t328** [sigstore/rekor#1581]
**Question**
How important is it to start the rekor ledger in a projects lifecycle that it starts monitoring logs at the initial commit of a git repo? Should this be considered essential or optional? My belief is that starting it after X number of commits creates a gap in coverage of the supply chain and is thus a less good practice. But I am new to this project and could use clarification on this point.

**Comment by Hayden-IO** [comment]
A transparency log provides an auditable record of events once the log is in use. An artifact verifier should expect that a signed artifact will be present in a log in order to trust it, since the presence in the log means that the artifact signer can audit whether the event was legitimate. In the example of commit signatures, it would be up to whoever is verifying them to decide if they will trust previous commits without being uploaded to a log.

If you're interesting in signing git commits, I would take a look at the gitsign project or reach out on slack on #gitsign.
