### ISSUE TITLE
New Timestamp Format

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#315]
Issue to track new timestamping efforts

* will update shortly.

**Comment by dlorenc** [comment]
Let's use this issue to track the new timestamp format @asraa is working on!

**Comment by asraa** [comment]
Hi!

So for context, originally I hashed out and was working on a `TimestampNote` inspired by `SignedNote` that I was generalizing from Bob's impl of the `SignedCheckpoint`. The TimestampNote would follow the roughtime protocol and include a blind, radius, etc. 

However, I think we may as well use Roughtime structs following https://github.com/cloudflare/roughtime so that when Rekor is fully production and we have a time source locked down, we would be ready to formally integrate it into the ecosystem and add a PR here https://github.com/cloudflare/roughtime/tree/1fe56bcbcfd4dd1ed52614ccc73a29c9b062275d#ecosystem-guidelines

**Comment by Hayden-IO** [comment]
There are newer issues, closing as outdated
