### ISSUE TITLE
Signed Note verification question

### ISSUE THREAD

**Issue by asraa** [sigstore/rekor#389]
When verifying SignedNotes, we never check that the loaded public key matches the hash. 

I think the only purpose is for easy lookup and early rejection in case none of the known public keys match the hash in the `note.Signature`. Shouldn't be a bad thing, right? WDYT?
(e.g. this would fail: a valid signature for a loaded public key, but the note.Signature specifies a different public key.)

https://github.com/sigstore/rekor/blob/07c8e8fda381c18af6d86dca273d4494bfd4cb5e/pkg/util/signed_note.go#L75

@bobcallaway

**Comment by bobcallaway** [comment]
meh... feels like an optimization to check; if signed notes were large then I could see saving the hash pass over the entire message (large) VS that of the public key (small)... 

I wouldn't reject a PR to add this; the only situation I can think of (easily) is if someone put a public key into an X509 code signing cert and incorrectly hashed the entire cert (instead of the embedded key), putting the first 4 bytes into the signature hint. The hint wouldn't match but the verification logic would generate the correct verification result.

**Comment by Hayden-IO** [comment]
@asraa good to close, this seems outdated?

**Comment by asraa** [comment]
This is still an open thing, but again, is not a security issue and an optimization. We can close as not relevant though.

**Comment by Hayden-IO** [comment]
If you want, we can leave open as a candidate for "good first issue".

**Comment by dcode333** [comment]
@asraa @haydentherapper  I want to contribute to this issue ..Can you guide please??

**Comment by asraa** [comment]
Hey! Notice that when we create a SignedNote we add a hash of the pk calculated like this:
https://github.com/sigstore/rekor/blob/07c8e8fda381c18af6d86dca273d4494bfd4cb5e/pkg/util/signed_note.go#L65

In Verify, you could also calculate the hash of the [pk](https://github.com/sigstore/rekor/blob/07c8e8fda381c18af6d86dca273d4494bfd4cb5e/pkg/util/signed_note.go#L88) and check the `SignedNote.Hash` matches.

**Comment by hojoungjang** [comment]
Hi, I did not see any further activity on this thread for a while and took a stab at this issue. 
@asraa PTAL when you get a chance.

**Comment by asraa** [comment]
I'm no longer maintaining the project, but thank you for the PR! I'm sure other codeowners will chime in on the PR
