### ISSUE TITLE
Support UUID --> shard ID parsing

### ISSUE THREAD

**Issue by lkatalin** [sigstore/rekor#487]
Goal: support parsing the UUID during GET calls to determine which log to query (with defaulting for the 0 case here). This would require two changes:

- [x] During upload of an entry, the UUID created should include a parseable log ID. For example, if the active log has log ID 163, the UUID might look like: `163-d2f305428d7c222d7b77f56453dd4b6e6851752ecacc78e5992779c8f9b61dd9`, where the number before the `-` separator is the log ID.

- [ ] Then during handling of a GET request for a particular UUID, the log ID can be easily determined and the request routed accordingly.

@dlorenc @bobcallaway Does this sound right to you based on the design?

**Comment by bobcallaway** [comment]
Perhaps a nit, but the term "log ID" is already in use in [rekor](https://github.com/sigstore/rekor/blob/4fcdcaa58fd5263560a82978d781eb64f5c5f93c/openapi.yaml#L438),  [trillian](https://github.com/google/trillian/blob/c1b0472ea95edc1bafc56a07986241bf461d4433/trillian_log_api.pb.go#L107) and [RFC6962](https://datatracker.ietf.org/doc/html/rfc6962#section-3.2) - so I would rather we call it "partition ID" or "shard ID". 

> Goal: support parsing the UUID during GET calls to determine which log to query (with defaulting for the 0 case here). This would require two changes:
> 
> * [ ]  During upload of an entry, the UUID created should include a parseable log ID. For example, if the active log has log ID 163, the UUID might look like: `163-d2f305428d7c222d7b77f56453dd4b6e6851752ecacc78e5992779c8f9b61dd9`, where the number before the `-` separator is the log ID.

Am I correct in saying that in order to handle the case for backward compatibility) if no shard ID is specified, default to the current log (i.e. shard 0)?

> * [ ]  Then during handling of a GET request for a particular UUID, the log ID can be easily determined and the request routed accordingly.
> 
> @dlorenc @bobcallaway Does this sound right to you based on the design?

yes, this aligns with what I had thought of in the design doc

**Comment by dlorenc** [comment]
+1, this all sounds right!

**Comment by lkatalin** [comment]
Note: make sure UUID will never use the separator char we are using.
