### ISSUE TITLE
rekor: cannot sign big files - fails with "Request Entity Too Large"

### ISSUE THREAD

**Issue by sylvestre** [sigstore/rekor#780]
Recent regression (around April 15th). 
Trying to upload a large file (119M) start fails with:

```
/home/jenkins/rekor upload --rekor_server https://rekor.sigstore.dev/ --signature /srv/repository/hirsute/pool/main/l/llvm-toolchain-snapshot/llvm-toolchain-snapshot_15~++20220418083928+15650b320bf6.orig.tar.xz.asc --public-key /home/jenkins/sigstore.public.key --artifact https://apt.llvm.org/hirsute/pool/main/l/llvm-toolchain-snapshot/llvm-toolchain-snapshot_15~++20220418083928+15650b320bf6.orig.tar.xz
[POST /api/v1/log/entries][413] createLogEntry default  &{Code:413 Message:Request Entity Too Large}
```

**Comment by asraa** [comment]
Hey, that's pretty close to the upper limit of the public instance

https://github.com/sigstore/rekor/issues/601#issuecomment-1021336377

Unfortunately, verifying PGP requires the full message because of the libraries we are using. That's a problem in itself (https://github.com/sigstore/rekor/issues/286)

We have fixed this problem for x509 type signatures (https://github.com/sigstore/rekor/issues/489)
