### ISSUE TITLE
Improve the timestamping authority PKI

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#798]
**Description**

Currently, we must manually update the timestamping authority certificate chain every 6 months. Additionally, each instance of Rekor generates its own signing certificate on startup, so it is difficult to fetch the chain that can verify a TSA response (1/number-of-instances), and it's not possible to fetch a chain once the server has rebooted.

We'll do what we did with Fulcio, long-lived certificates with a signer from a Cloud provider.

Design doc: https://docs.google.com/document/d/10dH80eTBdzf0yEuj96MpE8pq1VERPMJLY3VOxa3cfp8/edit?resourcekey=0-CxddIHfLz7KXXnZ9J2Vrmg#

**Comment by Hayden-IO** [comment]
cc @asraa

**Comment by asraa** [comment]
> we will handle this by adding the TSA intermediate and signing certificates to TUF. Rekor will pull the certificate chain from TUF, and clients will be expected to verify the certificate chain using TUF.

This is coming from option 3 which I agree is the best case. What I like about this is that we can attach a `Timestamp` usage to this, which will also allow people to configure another TSA for their timestamps rather than Rekor's built in SET.

I think that Cosign should also VerifySET against a TSA cert chain. I think the current API is against Rekor's key. Overall I like separating Rekor from it's TSA service.
