### ISSUE TITLE
How to run rekor-server, rekor-cli, trillian_log_signer  packages using docker?

### ISSUE THREAD

**Issue by mayurwaghmode** [sigstore/rekor#896]
**How to run the rekor-server image uploaded as part of GitHub container registry?**

Commands followed
```
 arch
x86_64

docker pull ghcr.io/sigstore/rekor/rekor-server:sha256-9e9e558a949ec59569073333693898de08b54f19cae361f3f836f59dce9c3e7e.sbom
sha256-9e9e558a949ec59569073333693898de08b54f19cae361f3f836f59dce9c3e7e.sbom: Pulling from sigstore/rekor/rekor-server
dba5af06d68a: Extracting  82.32kB/82.32kB
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
```

**Comment by mayurwaghmode** [comment]
@dlorenc @bobcallaway do you have any pointers on this?

**Comment by bobcallaway** [comment]
You can see an example of how it is run within a docker-compose setup at https://github.com/sigstore/rekor/blob/234afe786c8d41aea04818dddd38ffa2e891f56f/tests/issue-872-e2e-test.sh#L64, or checkout github.com/sigstore/scaffolding for how to run under kubernetes. 

Your command above is trying to run an sbom that is stored inside the container registry, which won’t work because the sbom describes the contents of the image, but does not contain the executable itself.

**Comment by Hayden-IO** [comment]
Closing, if you have more questions, come chat on slack!
